sudo: rquired
language: generic
services:
  - docker

before_install:
  - docker build -t kumarvgit/docker-react-nginx -f Dockerfile.dev .

script:
  - docker run -e CI=true kumarvdocker/docker-react-nginx npm run test